// Code generated by ent, DO NOT EDIT.

package clienttemplate

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/loopholelabs/endkey/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContainsFold(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldName, v))
}

// CommonName applies equality check predicate on the "common_name" field. It's identical to CommonNameEQ.
func CommonName(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldCommonName, v))
}

// Tag applies equality check predicate on the "tag" field. It's identical to TagEQ.
func Tag(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldTag, v))
}

// Validity applies equality check predicate on the "validity" field. It's identical to ValidityEQ.
func Validity(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldValidity, v))
}

// AllowAdditionalDNSNames applies equality check predicate on the "allow_additional_dns_names" field. It's identical to AllowAdditionalDNSNamesEQ.
func AllowAdditionalDNSNames(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldAllowAdditionalDNSNames, v))
}

// AllowAdditionalIps applies equality check predicate on the "allow_additional_ips" field. It's identical to AllowAdditionalIpsEQ.
func AllowAdditionalIps(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldAllowAdditionalIps, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContainsFold(FieldName, v))
}

// CommonNameEQ applies the EQ predicate on the "common_name" field.
func CommonNameEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldCommonName, v))
}

// CommonNameNEQ applies the NEQ predicate on the "common_name" field.
func CommonNameNEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldCommonName, v))
}

// CommonNameIn applies the In predicate on the "common_name" field.
func CommonNameIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldCommonName, vs...))
}

// CommonNameNotIn applies the NotIn predicate on the "common_name" field.
func CommonNameNotIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldCommonName, vs...))
}

// CommonNameGT applies the GT predicate on the "common_name" field.
func CommonNameGT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldCommonName, v))
}

// CommonNameGTE applies the GTE predicate on the "common_name" field.
func CommonNameGTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldCommonName, v))
}

// CommonNameLT applies the LT predicate on the "common_name" field.
func CommonNameLT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldCommonName, v))
}

// CommonNameLTE applies the LTE predicate on the "common_name" field.
func CommonNameLTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldCommonName, v))
}

// CommonNameContains applies the Contains predicate on the "common_name" field.
func CommonNameContains(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContains(FieldCommonName, v))
}

// CommonNameHasPrefix applies the HasPrefix predicate on the "common_name" field.
func CommonNameHasPrefix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasPrefix(FieldCommonName, v))
}

// CommonNameHasSuffix applies the HasSuffix predicate on the "common_name" field.
func CommonNameHasSuffix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasSuffix(FieldCommonName, v))
}

// CommonNameEqualFold applies the EqualFold predicate on the "common_name" field.
func CommonNameEqualFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEqualFold(FieldCommonName, v))
}

// CommonNameContainsFold applies the ContainsFold predicate on the "common_name" field.
func CommonNameContainsFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContainsFold(FieldCommonName, v))
}

// TagEQ applies the EQ predicate on the "tag" field.
func TagEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldTag, v))
}

// TagNEQ applies the NEQ predicate on the "tag" field.
func TagNEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldTag, v))
}

// TagIn applies the In predicate on the "tag" field.
func TagIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldTag, vs...))
}

// TagNotIn applies the NotIn predicate on the "tag" field.
func TagNotIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldTag, vs...))
}

// TagGT applies the GT predicate on the "tag" field.
func TagGT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldTag, v))
}

// TagGTE applies the GTE predicate on the "tag" field.
func TagGTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldTag, v))
}

// TagLT applies the LT predicate on the "tag" field.
func TagLT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldTag, v))
}

// TagLTE applies the LTE predicate on the "tag" field.
func TagLTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldTag, v))
}

// TagContains applies the Contains predicate on the "tag" field.
func TagContains(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContains(FieldTag, v))
}

// TagHasPrefix applies the HasPrefix predicate on the "tag" field.
func TagHasPrefix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasPrefix(FieldTag, v))
}

// TagHasSuffix applies the HasSuffix predicate on the "tag" field.
func TagHasSuffix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasSuffix(FieldTag, v))
}

// TagEqualFold applies the EqualFold predicate on the "tag" field.
func TagEqualFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEqualFold(FieldTag, v))
}

// TagContainsFold applies the ContainsFold predicate on the "tag" field.
func TagContainsFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContainsFold(FieldTag, v))
}

// ValidityEQ applies the EQ predicate on the "validity" field.
func ValidityEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldValidity, v))
}

// ValidityNEQ applies the NEQ predicate on the "validity" field.
func ValidityNEQ(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldValidity, v))
}

// ValidityIn applies the In predicate on the "validity" field.
func ValidityIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIn(FieldValidity, vs...))
}

// ValidityNotIn applies the NotIn predicate on the "validity" field.
func ValidityNotIn(vs ...string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotIn(FieldValidity, vs...))
}

// ValidityGT applies the GT predicate on the "validity" field.
func ValidityGT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGT(FieldValidity, v))
}

// ValidityGTE applies the GTE predicate on the "validity" field.
func ValidityGTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldGTE(FieldValidity, v))
}

// ValidityLT applies the LT predicate on the "validity" field.
func ValidityLT(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLT(FieldValidity, v))
}

// ValidityLTE applies the LTE predicate on the "validity" field.
func ValidityLTE(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldLTE(FieldValidity, v))
}

// ValidityContains applies the Contains predicate on the "validity" field.
func ValidityContains(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContains(FieldValidity, v))
}

// ValidityHasPrefix applies the HasPrefix predicate on the "validity" field.
func ValidityHasPrefix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasPrefix(FieldValidity, v))
}

// ValidityHasSuffix applies the HasSuffix predicate on the "validity" field.
func ValidityHasSuffix(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldHasSuffix(FieldValidity, v))
}

// ValidityEqualFold applies the EqualFold predicate on the "validity" field.
func ValidityEqualFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEqualFold(FieldValidity, v))
}

// ValidityContainsFold applies the ContainsFold predicate on the "validity" field.
func ValidityContainsFold(v string) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldContainsFold(FieldValidity, v))
}

// DNSNamesIsNil applies the IsNil predicate on the "dns_names" field.
func DNSNamesIsNil() predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIsNull(FieldDNSNames))
}

// DNSNamesNotNil applies the NotNil predicate on the "dns_names" field.
func DNSNamesNotNil() predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotNull(FieldDNSNames))
}

// AllowAdditionalDNSNamesEQ applies the EQ predicate on the "allow_additional_dns_names" field.
func AllowAdditionalDNSNamesEQ(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldAllowAdditionalDNSNames, v))
}

// AllowAdditionalDNSNamesNEQ applies the NEQ predicate on the "allow_additional_dns_names" field.
func AllowAdditionalDNSNamesNEQ(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldAllowAdditionalDNSNames, v))
}

// IPAddressesIsNil applies the IsNil predicate on the "ip_addresses" field.
func IPAddressesIsNil() predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldIsNull(FieldIPAddresses))
}

// IPAddressesNotNil applies the NotNil predicate on the "ip_addresses" field.
func IPAddressesNotNil() predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNotNull(FieldIPAddresses))
}

// AllowAdditionalIpsEQ applies the EQ predicate on the "allow_additional_ips" field.
func AllowAdditionalIpsEQ(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldEQ(FieldAllowAdditionalIps, v))
}

// AllowAdditionalIpsNEQ applies the NEQ predicate on the "allow_additional_ips" field.
func AllowAdditionalIpsNEQ(v bool) predicate.ClientTemplate {
	return predicate.ClientTemplate(sql.FieldNEQ(FieldAllowAdditionalIps, v))
}

// HasAuthority applies the HasEdge predicate on the "authority" edge.
func HasAuthority() predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AuthorityTable, AuthorityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorityWith applies the HasEdge predicate on the "authority" edge with a given conditions (other predicates).
func HasAuthorityWith(preds ...predicate.Authority) predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		step := newAuthorityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAPIKeys applies the HasEdge predicate on the "api_keys" edge.
func HasAPIKeys() predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, APIKeysTable, APIKeysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAPIKeysWith applies the HasEdge predicate on the "api_keys" edge with a given conditions (other predicates).
func HasAPIKeysWith(preds ...predicate.APIKey) predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		step := newAPIKeysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClientTemplate) predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for _, p := range predicates {
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClientTemplate) predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		s1 := s.Clone().SetP(nil)
		for i, p := range predicates {
			if i > 0 {
				s1.Or()
			}
			p(s1)
		}
		s.Where(s1.P())
	})
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClientTemplate) predicate.ClientTemplate {
	return predicate.ClientTemplate(func(s *sql.Selector) {
		p(s.Not())
	})
}
