// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loopholelabs/endkey/internal/ent/apikey"
	"github.com/loopholelabs/endkey/internal/ent/clienttemplate"
	"github.com/loopholelabs/endkey/internal/ent/predicate"
)

// ClientTemplateUpdate is the builder for updating ClientTemplate entities.
type ClientTemplateUpdate struct {
	config
	hooks    []Hook
	mutation *ClientTemplateMutation
}

// Where appends a list predicates to the ClientTemplateUpdate builder.
func (ctu *ClientTemplateUpdate) Where(ps ...predicate.ClientTemplate) *ClientTemplateUpdate {
	ctu.mutation.Where(ps...)
	return ctu
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (ctu *ClientTemplateUpdate) AddAPIKeyIDs(ids ...string) *ClientTemplateUpdate {
	ctu.mutation.AddAPIKeyIDs(ids...)
	return ctu
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (ctu *ClientTemplateUpdate) AddAPIKeys(a ...*APIKey) *ClientTemplateUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ctu.AddAPIKeyIDs(ids...)
}

// Mutation returns the ClientTemplateMutation object of the builder.
func (ctu *ClientTemplateUpdate) Mutation() *ClientTemplateMutation {
	return ctu.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (ctu *ClientTemplateUpdate) ClearAPIKeys() *ClientTemplateUpdate {
	ctu.mutation.ClearAPIKeys()
	return ctu
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (ctu *ClientTemplateUpdate) RemoveAPIKeyIDs(ids ...string) *ClientTemplateUpdate {
	ctu.mutation.RemoveAPIKeyIDs(ids...)
	return ctu
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (ctu *ClientTemplateUpdate) RemoveAPIKeys(a ...*APIKey) *ClientTemplateUpdate {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ctu.RemoveAPIKeyIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ctu *ClientTemplateUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, ctu.sqlSave, ctu.mutation, ctu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctu *ClientTemplateUpdate) SaveX(ctx context.Context) int {
	affected, err := ctu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ctu *ClientTemplateUpdate) Exec(ctx context.Context) error {
	_, err := ctu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctu *ClientTemplateUpdate) ExecX(ctx context.Context) {
	if err := ctu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctu *ClientTemplateUpdate) check() error {
	if _, ok := ctu.mutation.AuthorityID(); ctu.mutation.AuthorityCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ClientTemplate.authority"`)
	}
	return nil
}

func (ctu *ClientTemplateUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := ctu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(clienttemplate.Table, clienttemplate.Columns, sqlgraph.NewFieldSpec(clienttemplate.FieldID, field.TypeString))
	if ps := ctu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ctu.mutation.DNSNamesCleared() {
		_spec.ClearField(clienttemplate.FieldDNSNames, field.TypeJSON)
	}
	if ctu.mutation.IPAddressesCleared() {
		_spec.ClearField(clienttemplate.FieldIPAddresses, field.TypeJSON)
	}
	if ctu.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctu.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !ctu.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctu.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ctu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clienttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	ctu.mutation.done = true
	return n, nil
}

// ClientTemplateUpdateOne is the builder for updating a single ClientTemplate entity.
type ClientTemplateUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClientTemplateMutation
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (ctuo *ClientTemplateUpdateOne) AddAPIKeyIDs(ids ...string) *ClientTemplateUpdateOne {
	ctuo.mutation.AddAPIKeyIDs(ids...)
	return ctuo
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (ctuo *ClientTemplateUpdateOne) AddAPIKeys(a ...*APIKey) *ClientTemplateUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ctuo.AddAPIKeyIDs(ids...)
}

// Mutation returns the ClientTemplateMutation object of the builder.
func (ctuo *ClientTemplateUpdateOne) Mutation() *ClientTemplateMutation {
	return ctuo.mutation
}

// ClearAPIKeys clears all "api_keys" edges to the APIKey entity.
func (ctuo *ClientTemplateUpdateOne) ClearAPIKeys() *ClientTemplateUpdateOne {
	ctuo.mutation.ClearAPIKeys()
	return ctuo
}

// RemoveAPIKeyIDs removes the "api_keys" edge to APIKey entities by IDs.
func (ctuo *ClientTemplateUpdateOne) RemoveAPIKeyIDs(ids ...string) *ClientTemplateUpdateOne {
	ctuo.mutation.RemoveAPIKeyIDs(ids...)
	return ctuo
}

// RemoveAPIKeys removes "api_keys" edges to APIKey entities.
func (ctuo *ClientTemplateUpdateOne) RemoveAPIKeys(a ...*APIKey) *ClientTemplateUpdateOne {
	ids := make([]string, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ctuo.RemoveAPIKeyIDs(ids...)
}

// Where appends a list predicates to the ClientTemplateUpdate builder.
func (ctuo *ClientTemplateUpdateOne) Where(ps ...predicate.ClientTemplate) *ClientTemplateUpdateOne {
	ctuo.mutation.Where(ps...)
	return ctuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (ctuo *ClientTemplateUpdateOne) Select(field string, fields ...string) *ClientTemplateUpdateOne {
	ctuo.fields = append([]string{field}, fields...)
	return ctuo
}

// Save executes the query and returns the updated ClientTemplate entity.
func (ctuo *ClientTemplateUpdateOne) Save(ctx context.Context) (*ClientTemplate, error) {
	return withHooks(ctx, ctuo.sqlSave, ctuo.mutation, ctuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (ctuo *ClientTemplateUpdateOne) SaveX(ctx context.Context) *ClientTemplate {
	node, err := ctuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (ctuo *ClientTemplateUpdateOne) Exec(ctx context.Context) error {
	_, err := ctuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctuo *ClientTemplateUpdateOne) ExecX(ctx context.Context) {
	if err := ctuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctuo *ClientTemplateUpdateOne) check() error {
	if _, ok := ctuo.mutation.AuthorityID(); ctuo.mutation.AuthorityCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "ClientTemplate.authority"`)
	}
	return nil
}

func (ctuo *ClientTemplateUpdateOne) sqlSave(ctx context.Context) (_node *ClientTemplate, err error) {
	if err := ctuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clienttemplate.Table, clienttemplate.Columns, sqlgraph.NewFieldSpec(clienttemplate.FieldID, field.TypeString))
	id, ok := ctuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ClientTemplate.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := ctuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clienttemplate.FieldID)
		for _, f := range fields {
			if !clienttemplate.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != clienttemplate.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := ctuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if ctuo.mutation.DNSNamesCleared() {
		_spec.ClearField(clienttemplate.FieldDNSNames, field.TypeJSON)
	}
	if ctuo.mutation.IPAddressesCleared() {
		_spec.ClearField(clienttemplate.FieldIPAddresses, field.TypeJSON)
	}
	if ctuo.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctuo.mutation.RemovedAPIKeysIDs(); len(nodes) > 0 && !ctuo.mutation.APIKeysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := ctuo.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClientTemplate{config: ctuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, ctuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clienttemplate.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	ctuo.mutation.done = true
	return _node, nil
}
