// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/loopholelabs/endkey/internal/ent/apikey"
	"github.com/loopholelabs/endkey/internal/ent/authority"
	"github.com/loopholelabs/endkey/internal/ent/clienttemplate"
)

// ClientTemplateCreate is the builder for creating a ClientTemplate entity.
type ClientTemplateCreate struct {
	config
	mutation *ClientTemplateMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (ctc *ClientTemplateCreate) SetCreatedAt(t time.Time) *ClientTemplateCreate {
	ctc.mutation.SetCreatedAt(t)
	return ctc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ctc *ClientTemplateCreate) SetNillableCreatedAt(t *time.Time) *ClientTemplateCreate {
	if t != nil {
		ctc.SetCreatedAt(*t)
	}
	return ctc
}

// SetIdentifier sets the "identifier" field.
func (ctc *ClientTemplateCreate) SetIdentifier(s string) *ClientTemplateCreate {
	ctc.mutation.SetIdentifier(s)
	return ctc
}

// SetCommonName sets the "common_name" field.
func (ctc *ClientTemplateCreate) SetCommonName(s string) *ClientTemplateCreate {
	ctc.mutation.SetCommonName(s)
	return ctc
}

// SetTag sets the "tag" field.
func (ctc *ClientTemplateCreate) SetTag(s string) *ClientTemplateCreate {
	ctc.mutation.SetTag(s)
	return ctc
}

// SetValidity sets the "validity" field.
func (ctc *ClientTemplateCreate) SetValidity(s string) *ClientTemplateCreate {
	ctc.mutation.SetValidity(s)
	return ctc
}

// SetDNSNames sets the "dns_names" field.
func (ctc *ClientTemplateCreate) SetDNSNames(s []string) *ClientTemplateCreate {
	ctc.mutation.SetDNSNames(s)
	return ctc
}

// SetAllowAdditionalDNSNames sets the "allow_additional_dns_names" field.
func (ctc *ClientTemplateCreate) SetAllowAdditionalDNSNames(b bool) *ClientTemplateCreate {
	ctc.mutation.SetAllowAdditionalDNSNames(b)
	return ctc
}

// SetNillableAllowAdditionalDNSNames sets the "allow_additional_dns_names" field if the given value is not nil.
func (ctc *ClientTemplateCreate) SetNillableAllowAdditionalDNSNames(b *bool) *ClientTemplateCreate {
	if b != nil {
		ctc.SetAllowAdditionalDNSNames(*b)
	}
	return ctc
}

// SetIPAddresses sets the "ip_addresses" field.
func (ctc *ClientTemplateCreate) SetIPAddresses(s []string) *ClientTemplateCreate {
	ctc.mutation.SetIPAddresses(s)
	return ctc
}

// SetAllowAdditionalIps sets the "allow_additional_ips" field.
func (ctc *ClientTemplateCreate) SetAllowAdditionalIps(b bool) *ClientTemplateCreate {
	ctc.mutation.SetAllowAdditionalIps(b)
	return ctc
}

// SetNillableAllowAdditionalIps sets the "allow_additional_ips" field if the given value is not nil.
func (ctc *ClientTemplateCreate) SetNillableAllowAdditionalIps(b *bool) *ClientTemplateCreate {
	if b != nil {
		ctc.SetAllowAdditionalIps(*b)
	}
	return ctc
}

// SetAuthorityID sets the "authority" edge to the Authority entity by ID.
func (ctc *ClientTemplateCreate) SetAuthorityID(id int) *ClientTemplateCreate {
	ctc.mutation.SetAuthorityID(id)
	return ctc
}

// SetAuthority sets the "authority" edge to the Authority entity.
func (ctc *ClientTemplateCreate) SetAuthority(a *Authority) *ClientTemplateCreate {
	return ctc.SetAuthorityID(a.ID)
}

// AddAPIKeyIDs adds the "api_keys" edge to the APIKey entity by IDs.
func (ctc *ClientTemplateCreate) AddAPIKeyIDs(ids ...int) *ClientTemplateCreate {
	ctc.mutation.AddAPIKeyIDs(ids...)
	return ctc
}

// AddAPIKeys adds the "api_keys" edges to the APIKey entity.
func (ctc *ClientTemplateCreate) AddAPIKeys(a ...*APIKey) *ClientTemplateCreate {
	ids := make([]int, len(a))
	for i := range a {
		ids[i] = a[i].ID
	}
	return ctc.AddAPIKeyIDs(ids...)
}

// Mutation returns the ClientTemplateMutation object of the builder.
func (ctc *ClientTemplateCreate) Mutation() *ClientTemplateMutation {
	return ctc.mutation
}

// Save creates the ClientTemplate in the database.
func (ctc *ClientTemplateCreate) Save(ctx context.Context) (*ClientTemplate, error) {
	ctc.defaults()
	return withHooks(ctx, ctc.sqlSave, ctc.mutation, ctc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ctc *ClientTemplateCreate) SaveX(ctx context.Context) *ClientTemplate {
	v, err := ctc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ctc *ClientTemplateCreate) Exec(ctx context.Context) error {
	_, err := ctc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctc *ClientTemplateCreate) ExecX(ctx context.Context) {
	if err := ctc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ctc *ClientTemplateCreate) defaults() {
	if _, ok := ctc.mutation.CreatedAt(); !ok {
		v := clienttemplate.DefaultCreatedAt()
		ctc.mutation.SetCreatedAt(v)
	}
	if _, ok := ctc.mutation.AllowAdditionalDNSNames(); !ok {
		v := clienttemplate.DefaultAllowAdditionalDNSNames
		ctc.mutation.SetAllowAdditionalDNSNames(v)
	}
	if _, ok := ctc.mutation.AllowAdditionalIps(); !ok {
		v := clienttemplate.DefaultAllowAdditionalIps
		ctc.mutation.SetAllowAdditionalIps(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ctc *ClientTemplateCreate) check() error {
	if _, ok := ctc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ClientTemplate.created_at"`)}
	}
	if _, ok := ctc.mutation.Identifier(); !ok {
		return &ValidationError{Name: "identifier", err: errors.New(`ent: missing required field "ClientTemplate.identifier"`)}
	}
	if v, ok := ctc.mutation.Identifier(); ok {
		if err := clienttemplate.IdentifierValidator(v); err != nil {
			return &ValidationError{Name: "identifier", err: fmt.Errorf(`ent: validator failed for field "ClientTemplate.identifier": %w`, err)}
		}
	}
	if _, ok := ctc.mutation.CommonName(); !ok {
		return &ValidationError{Name: "common_name", err: errors.New(`ent: missing required field "ClientTemplate.common_name"`)}
	}
	if v, ok := ctc.mutation.CommonName(); ok {
		if err := clienttemplate.CommonNameValidator(v); err != nil {
			return &ValidationError{Name: "common_name", err: fmt.Errorf(`ent: validator failed for field "ClientTemplate.common_name": %w`, err)}
		}
	}
	if _, ok := ctc.mutation.Tag(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required field "ClientTemplate.tag"`)}
	}
	if v, ok := ctc.mutation.Tag(); ok {
		if err := clienttemplate.TagValidator(v); err != nil {
			return &ValidationError{Name: "tag", err: fmt.Errorf(`ent: validator failed for field "ClientTemplate.tag": %w`, err)}
		}
	}
	if _, ok := ctc.mutation.Validity(); !ok {
		return &ValidationError{Name: "validity", err: errors.New(`ent: missing required field "ClientTemplate.validity"`)}
	}
	if v, ok := ctc.mutation.Validity(); ok {
		if err := clienttemplate.ValidityValidator(v); err != nil {
			return &ValidationError{Name: "validity", err: fmt.Errorf(`ent: validator failed for field "ClientTemplate.validity": %w`, err)}
		}
	}
	if _, ok := ctc.mutation.AllowAdditionalDNSNames(); !ok {
		return &ValidationError{Name: "allow_additional_dns_names", err: errors.New(`ent: missing required field "ClientTemplate.allow_additional_dns_names"`)}
	}
	if _, ok := ctc.mutation.AllowAdditionalIps(); !ok {
		return &ValidationError{Name: "allow_additional_ips", err: errors.New(`ent: missing required field "ClientTemplate.allow_additional_ips"`)}
	}
	if _, ok := ctc.mutation.AuthorityID(); !ok {
		return &ValidationError{Name: "authority", err: errors.New(`ent: missing required edge "ClientTemplate.authority"`)}
	}
	return nil
}

func (ctc *ClientTemplateCreate) sqlSave(ctx context.Context) (*ClientTemplate, error) {
	if err := ctc.check(); err != nil {
		return nil, err
	}
	_node, _spec := ctc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ctc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	ctc.mutation.id = &_node.ID
	ctc.mutation.done = true
	return _node, nil
}

func (ctc *ClientTemplateCreate) createSpec() (*ClientTemplate, *sqlgraph.CreateSpec) {
	var (
		_node = &ClientTemplate{config: ctc.config}
		_spec = sqlgraph.NewCreateSpec(clienttemplate.Table, sqlgraph.NewFieldSpec(clienttemplate.FieldID, field.TypeInt))
	)
	if value, ok := ctc.mutation.CreatedAt(); ok {
		_spec.SetField(clienttemplate.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := ctc.mutation.Identifier(); ok {
		_spec.SetField(clienttemplate.FieldIdentifier, field.TypeString, value)
		_node.Identifier = value
	}
	if value, ok := ctc.mutation.CommonName(); ok {
		_spec.SetField(clienttemplate.FieldCommonName, field.TypeString, value)
		_node.CommonName = value
	}
	if value, ok := ctc.mutation.Tag(); ok {
		_spec.SetField(clienttemplate.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	if value, ok := ctc.mutation.Validity(); ok {
		_spec.SetField(clienttemplate.FieldValidity, field.TypeString, value)
		_node.Validity = value
	}
	if value, ok := ctc.mutation.DNSNames(); ok {
		_spec.SetField(clienttemplate.FieldDNSNames, field.TypeJSON, value)
		_node.DNSNames = value
	}
	if value, ok := ctc.mutation.AllowAdditionalDNSNames(); ok {
		_spec.SetField(clienttemplate.FieldAllowAdditionalDNSNames, field.TypeBool, value)
		_node.AllowAdditionalDNSNames = value
	}
	if value, ok := ctc.mutation.IPAddresses(); ok {
		_spec.SetField(clienttemplate.FieldIPAddresses, field.TypeJSON, value)
		_node.IPAddresses = value
	}
	if value, ok := ctc.mutation.AllowAdditionalIps(); ok {
		_spec.SetField(clienttemplate.FieldAllowAdditionalIps, field.TypeBool, value)
		_node.AllowAdditionalIps = value
	}
	if nodes := ctc.mutation.AuthorityIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clienttemplate.AuthorityTable,
			Columns: []string{clienttemplate.AuthorityColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authority.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.authority_client_templates = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ctc.mutation.APIKeysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   clienttemplate.APIKeysTable,
			Columns: []string{clienttemplate.APIKeysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(apikey.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ClientTemplateCreateBulk is the builder for creating many ClientTemplate entities in bulk.
type ClientTemplateCreateBulk struct {
	config
	builders []*ClientTemplateCreate
}

// Save creates the ClientTemplate entities in the database.
func (ctcb *ClientTemplateCreateBulk) Save(ctx context.Context) ([]*ClientTemplate, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ctcb.builders))
	nodes := make([]*ClientTemplate, len(ctcb.builders))
	mutators := make([]Mutator, len(ctcb.builders))
	for i := range ctcb.builders {
		func(i int, root context.Context) {
			builder := ctcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ClientTemplateMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ctcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ctcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ctcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ctcb *ClientTemplateCreateBulk) SaveX(ctx context.Context) []*ClientTemplate {
	v, err := ctcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ctcb *ClientTemplateCreateBulk) Exec(ctx context.Context) error {
	_, err := ctcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ctcb *ClientTemplateCreateBulk) ExecX(ctx context.Context) {
	if err := ctcb.Exec(ctx); err != nil {
		panic(err)
	}
}
