// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/loopholelabs/endkey/internal/ent/authority"
	"github.com/loopholelabs/endkey/internal/ent/template"
)

// Template is the model entity for the Template schema.
type Template struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// CommonName holds the value of the "common_name" field.
	CommonName string `json:"common_name,omitempty"`
	// Tag holds the value of the "tag" field.
	Tag string `json:"tag,omitempty"`
	// Validity holds the value of the "validity" field.
	Validity string `json:"validity,omitempty"`
	// DNSNames holds the value of the "dns_names" field.
	DNSNames []string `json:"dns_names,omitempty"`
	// AllowAdditionalDNSNames holds the value of the "allow_additional_dns_names" field.
	AllowAdditionalDNSNames bool `json:"allow_additional_dns_names,omitempty"`
	// IPAddresses holds the value of the "ip_addresses" field.
	IPAddresses []string `json:"ip_addresses,omitempty"`
	// AllowAdditionalIps holds the value of the "allow_additional_ips" field.
	AllowAdditionalIps bool `json:"allow_additional_ips,omitempty"`
	// AllowOverrideCommonName holds the value of the "allow_override_common_name" field.
	AllowOverrideCommonName bool `json:"allow_override_common_name,omitempty"`
	// Client holds the value of the "client" field.
	Client bool `json:"client,omitempty"`
	// Server holds the value of the "server" field.
	Server bool `json:"server,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TemplateQuery when eager-loading is set.
	Edges               TemplateEdges `json:"edges"`
	authority_templates *string
	selectValues        sql.SelectValues
}

// TemplateEdges holds the relations/edges for other nodes in the graph.
type TemplateEdges struct {
	// Authority holds the value of the authority edge.
	Authority *Authority `json:"authority,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// AuthorityOrErr returns the Authority value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TemplateEdges) AuthorityOrErr() (*Authority, error) {
	if e.loadedTypes[0] {
		if e.Authority == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: authority.Label}
		}
		return e.Authority, nil
	}
	return nil, &NotLoadedError{edge: "authority"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e TemplateEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[1] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Template) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case template.FieldDNSNames, template.FieldIPAddresses:
			values[i] = new([]byte)
		case template.FieldAllowAdditionalDNSNames, template.FieldAllowAdditionalIps, template.FieldAllowOverrideCommonName, template.FieldClient, template.FieldServer:
			values[i] = new(sql.NullBool)
		case template.FieldID, template.FieldName, template.FieldCommonName, template.FieldTag, template.FieldValidity:
			values[i] = new(sql.NullString)
		case template.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case template.ForeignKeys[0]: // authority_templates
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Template fields.
func (t *Template) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case template.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				t.ID = value.String
			}
		case template.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				t.CreatedAt = value.Time
			}
		case template.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				t.Name = value.String
			}
		case template.FieldCommonName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field common_name", values[i])
			} else if value.Valid {
				t.CommonName = value.String
			}
		case template.FieldTag:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tag", values[i])
			} else if value.Valid {
				t.Tag = value.String
			}
		case template.FieldValidity:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field validity", values[i])
			} else if value.Valid {
				t.Validity = value.String
			}
		case template.FieldDNSNames:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field dns_names", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &t.DNSNames); err != nil {
					return fmt.Errorf("unmarshal field dns_names: %w", err)
				}
			}
		case template.FieldAllowAdditionalDNSNames:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_additional_dns_names", values[i])
			} else if value.Valid {
				t.AllowAdditionalDNSNames = value.Bool
			}
		case template.FieldIPAddresses:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field ip_addresses", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &t.IPAddresses); err != nil {
					return fmt.Errorf("unmarshal field ip_addresses: %w", err)
				}
			}
		case template.FieldAllowAdditionalIps:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_additional_ips", values[i])
			} else if value.Valid {
				t.AllowAdditionalIps = value.Bool
			}
		case template.FieldAllowOverrideCommonName:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_override_common_name", values[i])
			} else if value.Valid {
				t.AllowOverrideCommonName = value.Bool
			}
		case template.FieldClient:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field client", values[i])
			} else if value.Valid {
				t.Client = value.Bool
			}
		case template.FieldServer:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field server", values[i])
			} else if value.Valid {
				t.Server = value.Bool
			}
		case template.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field authority_templates", values[i])
			} else if value.Valid {
				t.authority_templates = new(string)
				*t.authority_templates = value.String
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Template.
// This includes values selected through modifiers, order, etc.
func (t *Template) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryAuthority queries the "authority" edge of the Template entity.
func (t *Template) QueryAuthority() *AuthorityQuery {
	return NewTemplateClient(t.config).QueryAuthority(t)
}

// QueryAPIKeys queries the "api_keys" edge of the Template entity.
func (t *Template) QueryAPIKeys() *APIKeyQuery {
	return NewTemplateClient(t.config).QueryAPIKeys(t)
}

// Update returns a builder for updating this Template.
// Note that you need to call Template.Unwrap() before calling this method if this Template
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Template) Update() *TemplateUpdateOne {
	return NewTemplateClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Template entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Template) Unwrap() *Template {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Template is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Template) String() string {
	var builder strings.Builder
	builder.WriteString("Template(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("created_at=")
	builder.WriteString(t.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(t.Name)
	builder.WriteString(", ")
	builder.WriteString("common_name=")
	builder.WriteString(t.CommonName)
	builder.WriteString(", ")
	builder.WriteString("tag=")
	builder.WriteString(t.Tag)
	builder.WriteString(", ")
	builder.WriteString("validity=")
	builder.WriteString(t.Validity)
	builder.WriteString(", ")
	builder.WriteString("dns_names=")
	builder.WriteString(fmt.Sprintf("%v", t.DNSNames))
	builder.WriteString(", ")
	builder.WriteString("allow_additional_dns_names=")
	builder.WriteString(fmt.Sprintf("%v", t.AllowAdditionalDNSNames))
	builder.WriteString(", ")
	builder.WriteString("ip_addresses=")
	builder.WriteString(fmt.Sprintf("%v", t.IPAddresses))
	builder.WriteString(", ")
	builder.WriteString("allow_additional_ips=")
	builder.WriteString(fmt.Sprintf("%v", t.AllowAdditionalIps))
	builder.WriteString(", ")
	builder.WriteString("allow_override_common_name=")
	builder.WriteString(fmt.Sprintf("%v", t.AllowOverrideCommonName))
	builder.WriteString(", ")
	builder.WriteString("client=")
	builder.WriteString(fmt.Sprintf("%v", t.Client))
	builder.WriteString(", ")
	builder.WriteString("server=")
	builder.WriteString(fmt.Sprintf("%v", t.Server))
	builder.WriteByte(')')
	return builder.String()
}

// Templates is a parsable slice of Template.
type Templates []*Template
