// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/endkey/pkg/client/models"
)

// NewDeleteTemplateServerParams creates a new DeleteTemplateServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteTemplateServerParams() *DeleteTemplateServerParams {
	return &DeleteTemplateServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteTemplateServerParamsWithTimeout creates a new DeleteTemplateServerParams object
// with the ability to set a timeout on a request.
func NewDeleteTemplateServerParamsWithTimeout(timeout time.Duration) *DeleteTemplateServerParams {
	return &DeleteTemplateServerParams{
		timeout: timeout,
	}
}

// NewDeleteTemplateServerParamsWithContext creates a new DeleteTemplateServerParams object
// with the ability to set a context for a request.
func NewDeleteTemplateServerParamsWithContext(ctx context.Context) *DeleteTemplateServerParams {
	return &DeleteTemplateServerParams{
		Context: ctx,
	}
}

// NewDeleteTemplateServerParamsWithHTTPClient creates a new DeleteTemplateServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteTemplateServerParamsWithHTTPClient(client *http.Client) *DeleteTemplateServerParams {
	return &DeleteTemplateServerParams{
		HTTPClient: client,
	}
}

/*
DeleteTemplateServerParams contains all the parameters to send to the API endpoint

	for the delete template server operation.

	Typically these are written to a http.Request.
*/
type DeleteTemplateServerParams struct {

	/* Request.

	   Delete Server Template Request
	*/
	Request *models.ModelsDeleteServerTemplateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete template server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTemplateServerParams) WithDefaults() *DeleteTemplateServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete template server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteTemplateServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete template server params
func (o *DeleteTemplateServerParams) WithTimeout(timeout time.Duration) *DeleteTemplateServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete template server params
func (o *DeleteTemplateServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete template server params
func (o *DeleteTemplateServerParams) WithContext(ctx context.Context) *DeleteTemplateServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete template server params
func (o *DeleteTemplateServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete template server params
func (o *DeleteTemplateServerParams) WithHTTPClient(client *http.Client) *DeleteTemplateServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete template server params
func (o *DeleteTemplateServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the delete template server params
func (o *DeleteTemplateServerParams) WithRequest(request *models.ModelsDeleteServerTemplateRequest) *DeleteTemplateServerParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the delete template server params
func (o *DeleteTemplateServerParams) SetRequest(request *models.ModelsDeleteServerTemplateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteTemplateServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
