// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetTemplateClientAuthorityParams creates a new GetTemplateClientAuthorityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetTemplateClientAuthorityParams() *GetTemplateClientAuthorityParams {
	return &GetTemplateClientAuthorityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetTemplateClientAuthorityParamsWithTimeout creates a new GetTemplateClientAuthorityParams object
// with the ability to set a timeout on a request.
func NewGetTemplateClientAuthorityParamsWithTimeout(timeout time.Duration) *GetTemplateClientAuthorityParams {
	return &GetTemplateClientAuthorityParams{
		timeout: timeout,
	}
}

// NewGetTemplateClientAuthorityParamsWithContext creates a new GetTemplateClientAuthorityParams object
// with the ability to set a context for a request.
func NewGetTemplateClientAuthorityParamsWithContext(ctx context.Context) *GetTemplateClientAuthorityParams {
	return &GetTemplateClientAuthorityParams{
		Context: ctx,
	}
}

// NewGetTemplateClientAuthorityParamsWithHTTPClient creates a new GetTemplateClientAuthorityParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetTemplateClientAuthorityParamsWithHTTPClient(client *http.Client) *GetTemplateClientAuthorityParams {
	return &GetTemplateClientAuthorityParams{
		HTTPClient: client,
	}
}

/*
GetTemplateClientAuthorityParams contains all the parameters to send to the API endpoint

	for the get template client authority operation.

	Typically these are written to a http.Request.
*/
type GetTemplateClientAuthorityParams struct {

	/* Authority.

	   Authority Identifier
	*/
	Authority string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get template client authority params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTemplateClientAuthorityParams) WithDefaults() *GetTemplateClientAuthorityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get template client authority params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetTemplateClientAuthorityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get template client authority params
func (o *GetTemplateClientAuthorityParams) WithTimeout(timeout time.Duration) *GetTemplateClientAuthorityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get template client authority params
func (o *GetTemplateClientAuthorityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get template client authority params
func (o *GetTemplateClientAuthorityParams) WithContext(ctx context.Context) *GetTemplateClientAuthorityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get template client authority params
func (o *GetTemplateClientAuthorityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get template client authority params
func (o *GetTemplateClientAuthorityParams) WithHTTPClient(client *http.Client) *GetTemplateClientAuthorityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get template client authority params
func (o *GetTemplateClientAuthorityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthority adds the authority to the get template client authority params
func (o *GetTemplateClientAuthorityParams) WithAuthority(authority string) *GetTemplateClientAuthorityParams {
	o.SetAuthority(authority)
	return o
}

// SetAuthority adds the authority to the get template client authority params
func (o *GetTemplateClientAuthorityParams) SetAuthority(authority string) {
	o.Authority = authority
}

// WriteToRequest writes these params to a swagger request
func (o *GetTemplateClientAuthorityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param authority
	if err := r.SetPathParam("authority", o.Authority); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
