// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/endkey/pkg/client/models"
)

// GetTemplateClientAuthorityNameReader is a Reader for the GetTemplateClientAuthorityName structure.
type GetTemplateClientAuthorityNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetTemplateClientAuthorityNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetTemplateClientAuthorityNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewGetTemplateClientAuthorityNameBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewGetTemplateClientAuthorityNameUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewGetTemplateClientAuthorityNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewGetTemplateClientAuthorityNameConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 412:
		result := NewGetTemplateClientAuthorityNamePreconditionFailed()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewGetTemplateClientAuthorityNameInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[GET /template/client/{authority_name}] GetTemplateClientAuthorityName", response, response.Code())
	}
}

// NewGetTemplateClientAuthorityNameOK creates a GetTemplateClientAuthorityNameOK with default headers values
func NewGetTemplateClientAuthorityNameOK() *GetTemplateClientAuthorityNameOK {
	return &GetTemplateClientAuthorityNameOK{}
}

/*
GetTemplateClientAuthorityNameOK describes a response with status code 200, with default header values.

OK
*/
type GetTemplateClientAuthorityNameOK struct {
	Payload []*models.ModelsClientTemplateResponse
}

// IsSuccess returns true when this get template client authority name o k response has a 2xx status code
func (o *GetTemplateClientAuthorityNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get template client authority name o k response has a 3xx status code
func (o *GetTemplateClientAuthorityNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name o k response has a 4xx status code
func (o *GetTemplateClientAuthorityNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get template client authority name o k response has a 5xx status code
func (o *GetTemplateClientAuthorityNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name o k response a status code equal to that given
func (o *GetTemplateClientAuthorityNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get template client authority name o k response
func (o *GetTemplateClientAuthorityNameOK) Code() int {
	return 200
}

func (o *GetTemplateClientAuthorityNameOK) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameOK  %+v", 200, o.Payload)
}

func (o *GetTemplateClientAuthorityNameOK) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameOK  %+v", 200, o.Payload)
}

func (o *GetTemplateClientAuthorityNameOK) GetPayload() []*models.ModelsClientTemplateResponse {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNameBadRequest creates a GetTemplateClientAuthorityNameBadRequest with default headers values
func NewGetTemplateClientAuthorityNameBadRequest() *GetTemplateClientAuthorityNameBadRequest {
	return &GetTemplateClientAuthorityNameBadRequest{}
}

/*
GetTemplateClientAuthorityNameBadRequest describes a response with status code 400, with default header values.

Bad Request
*/
type GetTemplateClientAuthorityNameBadRequest struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name bad request response has a 2xx status code
func (o *GetTemplateClientAuthorityNameBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name bad request response has a 3xx status code
func (o *GetTemplateClientAuthorityNameBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name bad request response has a 4xx status code
func (o *GetTemplateClientAuthorityNameBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template client authority name bad request response has a 5xx status code
func (o *GetTemplateClientAuthorityNameBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name bad request response a status code equal to that given
func (o *GetTemplateClientAuthorityNameBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the get template client authority name bad request response
func (o *GetTemplateClientAuthorityNameBadRequest) Code() int {
	return 400
}

func (o *GetTemplateClientAuthorityNameBadRequest) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameBadRequest  %+v", 400, o.Payload)
}

func (o *GetTemplateClientAuthorityNameBadRequest) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameBadRequest  %+v", 400, o.Payload)
}

func (o *GetTemplateClientAuthorityNameBadRequest) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNameUnauthorized creates a GetTemplateClientAuthorityNameUnauthorized with default headers values
func NewGetTemplateClientAuthorityNameUnauthorized() *GetTemplateClientAuthorityNameUnauthorized {
	return &GetTemplateClientAuthorityNameUnauthorized{}
}

/*
GetTemplateClientAuthorityNameUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type GetTemplateClientAuthorityNameUnauthorized struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name unauthorized response has a 2xx status code
func (o *GetTemplateClientAuthorityNameUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name unauthorized response has a 3xx status code
func (o *GetTemplateClientAuthorityNameUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name unauthorized response has a 4xx status code
func (o *GetTemplateClientAuthorityNameUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template client authority name unauthorized response has a 5xx status code
func (o *GetTemplateClientAuthorityNameUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name unauthorized response a status code equal to that given
func (o *GetTemplateClientAuthorityNameUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the get template client authority name unauthorized response
func (o *GetTemplateClientAuthorityNameUnauthorized) Code() int {
	return 401
}

func (o *GetTemplateClientAuthorityNameUnauthorized) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameUnauthorized  %+v", 401, o.Payload)
}

func (o *GetTemplateClientAuthorityNameUnauthorized) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameUnauthorized  %+v", 401, o.Payload)
}

func (o *GetTemplateClientAuthorityNameUnauthorized) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNameNotFound creates a GetTemplateClientAuthorityNameNotFound with default headers values
func NewGetTemplateClientAuthorityNameNotFound() *GetTemplateClientAuthorityNameNotFound {
	return &GetTemplateClientAuthorityNameNotFound{}
}

/*
GetTemplateClientAuthorityNameNotFound describes a response with status code 404, with default header values.

Not Found
*/
type GetTemplateClientAuthorityNameNotFound struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name not found response has a 2xx status code
func (o *GetTemplateClientAuthorityNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name not found response has a 3xx status code
func (o *GetTemplateClientAuthorityNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name not found response has a 4xx status code
func (o *GetTemplateClientAuthorityNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template client authority name not found response has a 5xx status code
func (o *GetTemplateClientAuthorityNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name not found response a status code equal to that given
func (o *GetTemplateClientAuthorityNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the get template client authority name not found response
func (o *GetTemplateClientAuthorityNameNotFound) Code() int {
	return 404
}

func (o *GetTemplateClientAuthorityNameNotFound) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameNotFound  %+v", 404, o.Payload)
}

func (o *GetTemplateClientAuthorityNameNotFound) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameNotFound  %+v", 404, o.Payload)
}

func (o *GetTemplateClientAuthorityNameNotFound) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNameConflict creates a GetTemplateClientAuthorityNameConflict with default headers values
func NewGetTemplateClientAuthorityNameConflict() *GetTemplateClientAuthorityNameConflict {
	return &GetTemplateClientAuthorityNameConflict{}
}

/*
GetTemplateClientAuthorityNameConflict describes a response with status code 409, with default header values.

Conflict
*/
type GetTemplateClientAuthorityNameConflict struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name conflict response has a 2xx status code
func (o *GetTemplateClientAuthorityNameConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name conflict response has a 3xx status code
func (o *GetTemplateClientAuthorityNameConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name conflict response has a 4xx status code
func (o *GetTemplateClientAuthorityNameConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template client authority name conflict response has a 5xx status code
func (o *GetTemplateClientAuthorityNameConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name conflict response a status code equal to that given
func (o *GetTemplateClientAuthorityNameConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the get template client authority name conflict response
func (o *GetTemplateClientAuthorityNameConflict) Code() int {
	return 409
}

func (o *GetTemplateClientAuthorityNameConflict) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameConflict  %+v", 409, o.Payload)
}

func (o *GetTemplateClientAuthorityNameConflict) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameConflict  %+v", 409, o.Payload)
}

func (o *GetTemplateClientAuthorityNameConflict) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNamePreconditionFailed creates a GetTemplateClientAuthorityNamePreconditionFailed with default headers values
func NewGetTemplateClientAuthorityNamePreconditionFailed() *GetTemplateClientAuthorityNamePreconditionFailed {
	return &GetTemplateClientAuthorityNamePreconditionFailed{}
}

/*
GetTemplateClientAuthorityNamePreconditionFailed describes a response with status code 412, with default header values.

Precondition Failed
*/
type GetTemplateClientAuthorityNamePreconditionFailed struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name precondition failed response has a 2xx status code
func (o *GetTemplateClientAuthorityNamePreconditionFailed) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name precondition failed response has a 3xx status code
func (o *GetTemplateClientAuthorityNamePreconditionFailed) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name precondition failed response has a 4xx status code
func (o *GetTemplateClientAuthorityNamePreconditionFailed) IsClientError() bool {
	return true
}

// IsServerError returns true when this get template client authority name precondition failed response has a 5xx status code
func (o *GetTemplateClientAuthorityNamePreconditionFailed) IsServerError() bool {
	return false
}

// IsCode returns true when this get template client authority name precondition failed response a status code equal to that given
func (o *GetTemplateClientAuthorityNamePreconditionFailed) IsCode(code int) bool {
	return code == 412
}

// Code gets the status code for the get template client authority name precondition failed response
func (o *GetTemplateClientAuthorityNamePreconditionFailed) Code() int {
	return 412
}

func (o *GetTemplateClientAuthorityNamePreconditionFailed) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNamePreconditionFailed  %+v", 412, o.Payload)
}

func (o *GetTemplateClientAuthorityNamePreconditionFailed) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNamePreconditionFailed  %+v", 412, o.Payload)
}

func (o *GetTemplateClientAuthorityNamePreconditionFailed) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNamePreconditionFailed) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetTemplateClientAuthorityNameInternalServerError creates a GetTemplateClientAuthorityNameInternalServerError with default headers values
func NewGetTemplateClientAuthorityNameInternalServerError() *GetTemplateClientAuthorityNameInternalServerError {
	return &GetTemplateClientAuthorityNameInternalServerError{}
}

/*
GetTemplateClientAuthorityNameInternalServerError describes a response with status code 500, with default header values.

Internal Server Error
*/
type GetTemplateClientAuthorityNameInternalServerError struct {
	Payload string
}

// IsSuccess returns true when this get template client authority name internal server error response has a 2xx status code
func (o *GetTemplateClientAuthorityNameInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this get template client authority name internal server error response has a 3xx status code
func (o *GetTemplateClientAuthorityNameInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get template client authority name internal server error response has a 4xx status code
func (o *GetTemplateClientAuthorityNameInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this get template client authority name internal server error response has a 5xx status code
func (o *GetTemplateClientAuthorityNameInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this get template client authority name internal server error response a status code equal to that given
func (o *GetTemplateClientAuthorityNameInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the get template client authority name internal server error response
func (o *GetTemplateClientAuthorityNameInternalServerError) Code() int {
	return 500
}

func (o *GetTemplateClientAuthorityNameInternalServerError) Error() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetTemplateClientAuthorityNameInternalServerError) String() string {
	return fmt.Sprintf("[GET /template/client/{authority_name}][%d] getTemplateClientAuthorityNameInternalServerError  %+v", 500, o.Payload)
}

func (o *GetTemplateClientAuthorityNameInternalServerError) GetPayload() string {
	return o.Payload
}

func (o *GetTemplateClientAuthorityNameInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
