// Code generated by go-swagger; DO NOT EDIT.

package template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/endkey/pkg/client/models"
)

// NewPostTemplateParams creates a new PostTemplateParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostTemplateParams() *PostTemplateParams {
	return &PostTemplateParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostTemplateParamsWithTimeout creates a new PostTemplateParams object
// with the ability to set a timeout on a request.
func NewPostTemplateParamsWithTimeout(timeout time.Duration) *PostTemplateParams {
	return &PostTemplateParams{
		timeout: timeout,
	}
}

// NewPostTemplateParamsWithContext creates a new PostTemplateParams object
// with the ability to set a context for a request.
func NewPostTemplateParamsWithContext(ctx context.Context) *PostTemplateParams {
	return &PostTemplateParams{
		Context: ctx,
	}
}

// NewPostTemplateParamsWithHTTPClient creates a new PostTemplateParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostTemplateParamsWithHTTPClient(client *http.Client) *PostTemplateParams {
	return &PostTemplateParams{
		HTTPClient: client,
	}
}

/*
PostTemplateParams contains all the parameters to send to the API endpoint

	for the post template operation.

	Typically these are written to a http.Request.
*/
type PostTemplateParams struct {

	/* Request.

	   Create Template Request
	*/
	Request *models.ModelsCreateTemplateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTemplateParams) WithDefaults() *PostTemplateParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post template params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostTemplateParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post template params
func (o *PostTemplateParams) WithTimeout(timeout time.Duration) *PostTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post template params
func (o *PostTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post template params
func (o *PostTemplateParams) WithContext(ctx context.Context) *PostTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post template params
func (o *PostTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post template params
func (o *PostTemplateParams) WithHTTPClient(client *http.Client) *PostTemplateParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post template params
func (o *PostTemplateParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post template params
func (o *PostTemplateParams) WithRequest(request *models.ModelsCreateTemplateRequest) *PostTemplateParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post template params
func (o *PostTemplateParams) SetRequest(request *models.ModelsCreateTemplateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
