// Code generated by go-swagger; DO NOT EDIT.

package authority

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAuthorityIdentifierParams creates a new DeleteAuthorityIdentifierParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAuthorityIdentifierParams() *DeleteAuthorityIdentifierParams {
	return &DeleteAuthorityIdentifierParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAuthorityIdentifierParamsWithTimeout creates a new DeleteAuthorityIdentifierParams object
// with the ability to set a timeout on a request.
func NewDeleteAuthorityIdentifierParamsWithTimeout(timeout time.Duration) *DeleteAuthorityIdentifierParams {
	return &DeleteAuthorityIdentifierParams{
		timeout: timeout,
	}
}

// NewDeleteAuthorityIdentifierParamsWithContext creates a new DeleteAuthorityIdentifierParams object
// with the ability to set a context for a request.
func NewDeleteAuthorityIdentifierParamsWithContext(ctx context.Context) *DeleteAuthorityIdentifierParams {
	return &DeleteAuthorityIdentifierParams{
		Context: ctx,
	}
}

// NewDeleteAuthorityIdentifierParamsWithHTTPClient creates a new DeleteAuthorityIdentifierParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAuthorityIdentifierParamsWithHTTPClient(client *http.Client) *DeleteAuthorityIdentifierParams {
	return &DeleteAuthorityIdentifierParams{
		HTTPClient: client,
	}
}

/*
DeleteAuthorityIdentifierParams contains all the parameters to send to the API endpoint

	for the delete authority identifier operation.

	Typically these are written to a http.Request.
*/
type DeleteAuthorityIdentifierParams struct {

	/* Identifier.

	   Authority Identifier
	*/
	Identifier string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete authority identifier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAuthorityIdentifierParams) WithDefaults() *DeleteAuthorityIdentifierParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete authority identifier params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAuthorityIdentifierParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) WithTimeout(timeout time.Duration) *DeleteAuthorityIdentifierParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) WithContext(ctx context.Context) *DeleteAuthorityIdentifierParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) WithHTTPClient(client *http.Client) *DeleteAuthorityIdentifierParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIdentifier adds the identifier to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) WithIdentifier(identifier string) *DeleteAuthorityIdentifierParams {
	o.SetIdentifier(identifier)
	return o
}

// SetIdentifier adds the identifier to the delete authority identifier params
func (o *DeleteAuthorityIdentifierParams) SetIdentifier(identifier string) {
	o.Identifier = identifier
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAuthorityIdentifierParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param identifier
	if err := r.SetPathParam("identifier", o.Identifier); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
