// Code generated by go-swagger; DO NOT EDIT.

package authority

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthorityNameParams creates a new GetAuthorityNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAuthorityNameParams() *GetAuthorityNameParams {
	return &GetAuthorityNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAuthorityNameParamsWithTimeout creates a new GetAuthorityNameParams object
// with the ability to set a timeout on a request.
func NewGetAuthorityNameParamsWithTimeout(timeout time.Duration) *GetAuthorityNameParams {
	return &GetAuthorityNameParams{
		timeout: timeout,
	}
}

// NewGetAuthorityNameParamsWithContext creates a new GetAuthorityNameParams object
// with the ability to set a context for a request.
func NewGetAuthorityNameParamsWithContext(ctx context.Context) *GetAuthorityNameParams {
	return &GetAuthorityNameParams{
		Context: ctx,
	}
}

// NewGetAuthorityNameParamsWithHTTPClient creates a new GetAuthorityNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAuthorityNameParamsWithHTTPClient(client *http.Client) *GetAuthorityNameParams {
	return &GetAuthorityNameParams{
		HTTPClient: client,
	}
}

/*
GetAuthorityNameParams contains all the parameters to send to the API endpoint

	for the get authority name operation.

	Typically these are written to a http.Request.
*/
type GetAuthorityNameParams struct {

	/* Name.

	   Authority Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get authority name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorityNameParams) WithDefaults() *GetAuthorityNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get authority name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAuthorityNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get authority name params
func (o *GetAuthorityNameParams) WithTimeout(timeout time.Duration) *GetAuthorityNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get authority name params
func (o *GetAuthorityNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get authority name params
func (o *GetAuthorityNameParams) WithContext(ctx context.Context) *GetAuthorityNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get authority name params
func (o *GetAuthorityNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get authority name params
func (o *GetAuthorityNameParams) WithHTTPClient(client *http.Client) *GetAuthorityNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get authority name params
func (o *GetAuthorityNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the get authority name params
func (o *GetAuthorityNameParams) WithName(name string) *GetAuthorityNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get authority name params
func (o *GetAuthorityNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAuthorityNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
