// Code generated by go-swagger; DO NOT EDIT.

package rootkey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteRootkeyNameParams creates a new DeleteRootkeyNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteRootkeyNameParams() *DeleteRootkeyNameParams {
	return &DeleteRootkeyNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteRootkeyNameParamsWithTimeout creates a new DeleteRootkeyNameParams object
// with the ability to set a timeout on a request.
func NewDeleteRootkeyNameParamsWithTimeout(timeout time.Duration) *DeleteRootkeyNameParams {
	return &DeleteRootkeyNameParams{
		timeout: timeout,
	}
}

// NewDeleteRootkeyNameParamsWithContext creates a new DeleteRootkeyNameParams object
// with the ability to set a context for a request.
func NewDeleteRootkeyNameParamsWithContext(ctx context.Context) *DeleteRootkeyNameParams {
	return &DeleteRootkeyNameParams{
		Context: ctx,
	}
}

// NewDeleteRootkeyNameParamsWithHTTPClient creates a new DeleteRootkeyNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteRootkeyNameParamsWithHTTPClient(client *http.Client) *DeleteRootkeyNameParams {
	return &DeleteRootkeyNameParams{
		HTTPClient: client,
	}
}

/*
DeleteRootkeyNameParams contains all the parameters to send to the API endpoint

	for the delete rootkey name operation.

	Typically these are written to a http.Request.
*/
type DeleteRootkeyNameParams struct {

	/* Name.

	   Root Key Name
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete rootkey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRootkeyNameParams) WithDefaults() *DeleteRootkeyNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete rootkey name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteRootkeyNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete rootkey name params
func (o *DeleteRootkeyNameParams) WithTimeout(timeout time.Duration) *DeleteRootkeyNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete rootkey name params
func (o *DeleteRootkeyNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete rootkey name params
func (o *DeleteRootkeyNameParams) WithContext(ctx context.Context) *DeleteRootkeyNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete rootkey name params
func (o *DeleteRootkeyNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete rootkey name params
func (o *DeleteRootkeyNameParams) WithHTTPClient(client *http.Client) *DeleteRootkeyNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete rootkey name params
func (o *DeleteRootkeyNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithName adds the name to the delete rootkey name params
func (o *DeleteRootkeyNameParams) WithName(name string) *DeleteRootkeyNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the delete rootkey name params
func (o *DeleteRootkeyNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteRootkeyNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
