// Code generated by go-swagger; DO NOT EDIT.

package certificate

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/loopholelabs/endkey/pkg/client/models"
)

// NewPostCertificateServerParams creates a new PostCertificateServerParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostCertificateServerParams() *PostCertificateServerParams {
	return &PostCertificateServerParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostCertificateServerParamsWithTimeout creates a new PostCertificateServerParams object
// with the ability to set a timeout on a request.
func NewPostCertificateServerParamsWithTimeout(timeout time.Duration) *PostCertificateServerParams {
	return &PostCertificateServerParams{
		timeout: timeout,
	}
}

// NewPostCertificateServerParamsWithContext creates a new PostCertificateServerParams object
// with the ability to set a context for a request.
func NewPostCertificateServerParamsWithContext(ctx context.Context) *PostCertificateServerParams {
	return &PostCertificateServerParams{
		Context: ctx,
	}
}

// NewPostCertificateServerParamsWithHTTPClient creates a new PostCertificateServerParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostCertificateServerParamsWithHTTPClient(client *http.Client) *PostCertificateServerParams {
	return &PostCertificateServerParams{
		HTTPClient: client,
	}
}

/*
PostCertificateServerParams contains all the parameters to send to the API endpoint

	for the post certificate server operation.

	Typically these are written to a http.Request.
*/
type PostCertificateServerParams struct {

	/* Request.

	   Create Server Certificate Request
	*/
	Request *models.ModelsCreateServerCertificateRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post certificate server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCertificateServerParams) WithDefaults() *PostCertificateServerParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post certificate server params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostCertificateServerParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post certificate server params
func (o *PostCertificateServerParams) WithTimeout(timeout time.Duration) *PostCertificateServerParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post certificate server params
func (o *PostCertificateServerParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post certificate server params
func (o *PostCertificateServerParams) WithContext(ctx context.Context) *PostCertificateServerParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post certificate server params
func (o *PostCertificateServerParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post certificate server params
func (o *PostCertificateServerParams) WithHTTPClient(client *http.Client) *PostCertificateServerParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post certificate server params
func (o *PostCertificateServerParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithRequest adds the request to the post certificate server params
func (o *PostCertificateServerParams) WithRequest(request *models.ModelsCreateServerCertificateRequest) *PostCertificateServerParams {
	o.SetRequest(request)
	return o
}

// SetRequest adds the request to the post certificate server params
func (o *PostCertificateServerParams) SetRequest(request *models.ModelsCreateServerCertificateRequest) {
	o.Request = request
}

// WriteToRequest writes these params to a swagger request
func (o *PostCertificateServerParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Request != nil {
		if err := r.SetBodyParam(o.Request); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
