// Code generated by go-swagger; DO NOT EDIT.

package apikey

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetApikeyAuthorityParams creates a new GetApikeyAuthorityParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetApikeyAuthorityParams() *GetApikeyAuthorityParams {
	return &GetApikeyAuthorityParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetApikeyAuthorityParamsWithTimeout creates a new GetApikeyAuthorityParams object
// with the ability to set a timeout on a request.
func NewGetApikeyAuthorityParamsWithTimeout(timeout time.Duration) *GetApikeyAuthorityParams {
	return &GetApikeyAuthorityParams{
		timeout: timeout,
	}
}

// NewGetApikeyAuthorityParamsWithContext creates a new GetApikeyAuthorityParams object
// with the ability to set a context for a request.
func NewGetApikeyAuthorityParamsWithContext(ctx context.Context) *GetApikeyAuthorityParams {
	return &GetApikeyAuthorityParams{
		Context: ctx,
	}
}

// NewGetApikeyAuthorityParamsWithHTTPClient creates a new GetApikeyAuthorityParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetApikeyAuthorityParamsWithHTTPClient(client *http.Client) *GetApikeyAuthorityParams {
	return &GetApikeyAuthorityParams{
		HTTPClient: client,
	}
}

/*
GetApikeyAuthorityParams contains all the parameters to send to the API endpoint

	for the get apikey authority operation.

	Typically these are written to a http.Request.
*/
type GetApikeyAuthorityParams struct {

	/* Authority.

	   Authority Identifier
	*/
	Authority string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get apikey authority params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetApikeyAuthorityParams) WithDefaults() *GetApikeyAuthorityParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get apikey authority params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetApikeyAuthorityParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get apikey authority params
func (o *GetApikeyAuthorityParams) WithTimeout(timeout time.Duration) *GetApikeyAuthorityParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get apikey authority params
func (o *GetApikeyAuthorityParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get apikey authority params
func (o *GetApikeyAuthorityParams) WithContext(ctx context.Context) *GetApikeyAuthorityParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get apikey authority params
func (o *GetApikeyAuthorityParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get apikey authority params
func (o *GetApikeyAuthorityParams) WithHTTPClient(client *http.Client) *GetApikeyAuthorityParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get apikey authority params
func (o *GetApikeyAuthorityParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAuthority adds the authority to the get apikey authority params
func (o *GetApikeyAuthorityParams) WithAuthority(authority string) *GetApikeyAuthorityParams {
	o.SetAuthority(authority)
	return o
}

// SetAuthority adds the authority to the get apikey authority params
func (o *GetApikeyAuthorityParams) SetAuthority(authority string) {
	o.Authority = authority
}

// WriteToRequest writes these params to a swagger request
func (o *GetApikeyAuthorityParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param authority
	if err := r.SetPathParam("authority", o.Authority); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
